[package]
name = "outixs"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bitcoin = "0.30"
sha2 = "0.10"
reqwest = { version = "0.11", features = ["blocking"] }

[dev-dependencies]
# Add testing or mocking dependencies if needed in the future

[features]
# Add optional features or configurations as needed
