[package]
name = "outixs"
version = "0.1.0"
edition = "2021"
description = "A lightweight SDK for managing UTXOs, Nostr relays, and Bitcoin anchoring."
authors = ["Your Name <your.email@example.com>"]
license = "MIT"
repository = "https://github.com/wiard/Outixs-SDK"

[dependencies]
serde = { version = "1.0", features = ["derive"] } # For serialization and deserialization
bitcoin = "0.30"                                  # For handling Bitcoin transactions and UTXOs
sha2 = "0.10"                                     # For SHA-256 hashing
reqwest = { version = "0.11", features = ["blocking"] } # For HTTP requests (e.g., fetching UTXOs)

[dev-dependencies]
# Add dependencies for testing or mocking if required
tokio = { version = "1", features = ["full"] }    # For async testing (optional)
mockito = "0.30"                                  # For mocking HTTP responses in tests (optional)

[features]
default = [] # No default features for now; add as required
nostr = ["reqwest"] # Enable Nostr functionality (optional feature for relay communication)

[workspace]
# If you plan to expand the project into a workspace with multiple packages, include this section
members = ["outixs"]

